version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  db:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: '12345'
      MYSQL_DATABASE: 'projet_pfe'

volumes:
  mysql_data:
